### ISSUE TITLE
Implement StructuredClone polyfill in Angular applications

### ISSUE THREAD

**Issue by BenRacicot** [ungap/structured-clone#3]
Hello, I was hoping to get some guidance on implementing this polyfill within an Angular application. I would love to get it available app-wide via `polyfills.ts` (or some other way).

That being said, importing the module within a specific file causes TS errors related to missing typings. 

Do typings exist somewhere or perhaps I could help to create a `d.ts` for the structuredClone poly?

```
Could not find a declaration file for module '@ungap/structured-clone'. 'node_modules/@ungap/structured-clone/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/ungap__structured-clone` if it exists or add a new declaration (.d.ts) file containing `declare module '@ungap/structured-clone';`ts(7016)
```

**Comment by WebReflection** [comment]
types are here: https://github.com/ungap/structured-clone/blob/main/esm/index.js

to have this module as global you can:

```js
import structuredClone from '@ungap/structured-clone';
globalThis.structuredClone = structuredClone;
```

the default export is already the global utility if present or already globally polyfilled.

If you file a PR that produces through a *script* the `.d.ts` file for at least the index I'd be more than happy, but in general I don't TS and specially here it brings absolutely nothing to the plate because it's basically `T` in to `T` out, whatever `T` is, except it's a copy of the original `T`.

Other utilities are not part of the standard polyfill, so those shouldn't be an issue neither.

**Comment by mburger81** [comment]
@WebReflection

I declare the code in the angular `polyfills.ts` doing like described, but I'm running into this issue


```
ERROR Error: Uncaught (in promise): RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at index.js:19:46
    ........
    ........
```

**Comment by WebReflection** [comment]
I have zero code to test there ... can't help until I know what causes that ...

**Comment by mburger81** [comment]
I've created a new repository for testing, its mainly an empty angular project with the polyfill
https://github.com/mburger81/angular-structured-clone

In the last commit you can see mainly what I've done https://github.com/mburger81/angular-structured-clone/commit/4d7420bee8fc40efc3a9384a8a5f5dc7016fdf53

to run the project you just need to install packages and run command `npx ng serve`

open the app at http://localhost:4200 and In the console you'll see this issue

```
Uncaught RangeError: Maximum call stack size exceeded
    at index.js:19:46
    at index.js:19:46
    at index.js:19:46
    at index.js:19:46
    at index.js:19:46
    at index.js:19:46
    at index.js:19:46
    at index.js:19:46
    at index.js:19:46
    at index.js:19:46
```

**Comment by WebReflection** [comment]
is [this](https://github.com/mburger81/angular-structured-clone/blob/main/src/polyfills.ts#L58) the line that fails? if that's the case it looks like your bundling is doing dodgy stuff there ... otherwise, can you please provide the minimal amount of data that would cause that? this module is 100% test covered and tested against stuff that has been around for years, I am not sure what to look at with an Angular repository, sorry.

**Comment by ulken** [comment]
> ```sh
> Uncaught RangeError: Maximum call stack size exceeded
>     at index.js:19:46
>     ...
>     at index.js:19:46
> ```

I just got hit by the same error. In my case it came from upgrading Node 16 LTS to Node 18 LTS. `structuredClone` was added to Node in Node 17.

[This suggestion](https://github.com/ungap/structured-clone/issues/3#issuecomment-1005497915) (which I followed) was the culprit: 

```js
import structuredClone from '@ungap/structured-clone';
globalThis.structuredClone = structuredClone;
```

Removing the last line it works as expected. I suppose the polyfill check isn't 100 % solid or something. It ends up with infinite call recursion.

Clearly, I no longer need the polyfill since it's now natively supported, but I assume there might be cases where it would be preferable (and by definition of a polyfill?) for it to work in environments with and without a native implementation available.

**Comment by ulken** [comment]
Yeah, [looking closer](https://github.com/ungap/structured-clone/blob/main/cjs/index.js#L16) into it, it makes sense. 

```js
typeof structuredClone === "function" ?
  /* c8 ignore start */
  (any, options) => (
    options && ('json' in options || 'lossy' in options) ?
      deserialize(serialize(any, options)) : structuredClone(any)
  )
```

Since the check is done on-demand each time the function is called, and we now have reassigned the property on `globalThis` to call this function, it will just keep calling itself.

Either the suggestion above would need to be changed to:

```js
import structuredClone from '@ungap/structured-clone';

if (typeof structuredClone !== "function") {
  globalThis.structuredClone = structuredClone;
}
```

or the implementation would need to store a module local reference to the native function and not rely on it to be available/intact on `globalThis` whenever the function is called. Something like:

```js
const nativeStructuredClone = (globalThis.)structuredClone;
```

and check for its presence when the function is called:

```js
typeof nativeStructuredClone === "function" ? nativeStructuredClone(any) : ...
```

If you, @WebReflection, prefer the latter, I can submit a PR, but I'll await your response first.

**Comment by WebReflection** [comment]
there is nothing broken with this module or repository but maybe I've been to naive in suggesting [this solution](https://github.com/ungap/structured-clone/issues/3#issuecomment-1005497915), however:

  * a module in ECMAScript is never evaluated twice ... I don't understand why you say you run this module twice so it causes recursion ... this is your bundler/build-step problem, not this module one
  * change the suggestion into this and call it a day?

```js
import structuredClone from '@ungap/structured-clone';
if (!globalThis.structuredClone)
  globalThis.structuredClone = structuredClone;
```

this doesn't re-assign `structuredClone` to globalThis if not available or already patched, so that no recursion should ever happen... deal?

**Comment by andrew-pyle** [comment]
My first experience with this repository today was the infinite loop problem from above. I needed to polyfill the globally-available `structuredClone` function. I found it strange that there is no guidance on polyfilling the global `structuredClone` in the README, so I guessed this:

```js
import structuredClone from "@ungap/structured-clone";
window.structuredClone = structuredClone;
```
💥 Boom.

Infinite loop in Chrome, because Chrome already has a globally-available implementation of `structuredClone`.

Fixed with the guard, like above:
```js
import structuredClone from "@ungap/structured-clone";
if (!("structuredClone" in window)) {
  window.structuredClone = structuredClone;
}
```
@WebReflection Can we get something in the README describing that this polyfill's default export cannot be attached as-is globally? Or could we just show an example of the guarded global attachment?

I've opened PR #14 if you like my wording for the README.
